name: Deploy School ERP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Environment Variables
        run: |
          # Create the app directory if it doesn't exist (it should, but just in case)
          mkdir -p app
          # Copy the master env from your home directory into the app folder
          cp ~/configs/school-erp.env ./app/.env

      - name: Build and Restart Containers
        run: docker compose up -d --build --remove-orphans

      - name: Prune Old Images
        run: docker image prune -f
